### ISSUE TITLE
Use self-cleaning test fixtures

### ISSUE THREAD

**Issue by zkamvar** [ropensci/tinkr#25]
> should we use self-cleaning test fixtures? https://www.tidyverse.org/blog/2020/04/self-cleaning-test-fixtures/

Context: this package was developed before self-cleaning test fixtures via {withr} was a thing, but they definitely will help clean up the readability, so it's worth a small refactor :)

_Originally posted by @maelle in https://github.com/ropensci/tinkr/pull/24#discussion_r494794519_

**Comment by maelle** [comment]
And since this package isn't on CRAN yet, we can use testthat dev version and thus edition 3 (snapshot tests might be useful too in our case)

**Comment by maelle** [comment]
btw have you seen https://rstudio.com/resources/webinars/testthat-3/ @zkamvar?

**Comment by zkamvar** [comment]
YES! I am in full support of using this version and snapshot tests! If nothing else, having the emoji output when my tests pass is a real treat.

**Comment by maelle** [comment]
😀🎉🚀
