### ISSUE TITLE
Use R6 to store the object? 

### ISSUE THREAD

**Issue by zkamvar** [ropensci/tinkr#27]
This was brought up in a PR review:

> > I saw you're into R6 and I wonder whether that's the route we should go in tinkr too instead of using a list?
> 
> I'm ambivalent about this. I've found it to be quite useful for my own tasks and it reinforces the concept that {xml2} objects work by side-effect, but on the other hand, it may not be strictly necessary. I guess it depends on what the perceived audience will do with it. :shrug:

_Originally posted by @zkamvar in https://github.com/ropensci/tinkr/pull/24#issuecomment-699036027_

**Comment by maelle** [comment]
IMHO we wouldn't decrease the number of users by using R6 :wink:
