### ISSUE TITLE
Use github actions for building the site.

### ISSUE THREAD

**Issue by zkamvar** [ropensci/tinkr#29]
```r
usethis::use_github_action("pkgdown")
```

**Comment by maelle** [comment]
No need to https://ropensci.org/technotes/2019/06/07/ropensci-docs/ :-)

https://docs.ropensci.org/tinkr

**Comment by zkamvar** [comment]
Yay! Though, I think the redirect must have thrown Jenkins off since it hasn't updated since #22

**Comment by maelle** [comment]
Now it seems fine? https://dev.ropensci.org/job/tinkr/

**Comment by zkamvar** [comment]
It appears to have caught up. I guess it might have been an issue with the redirect needing to catch up on the Jenkins side.
