### ISSUE TITLE
Release to CRAN?

### ISSUE THREAD

**Issue by zkamvar** [ropensci/tinkr#43]
I think one of the things that was preventing us from releasing {tinkr} on CRAN previously was the format loss of brackets and tables. But now that we have those, I'm wondering if we should release it on CRAN (where the only thing that would prevent us from doing so is BDR). What features should we have before a CRAN release?

**Comment by zkamvar** [comment]
Part of my motivation for this is also that we bump the version so that {pegboard} can accurately state its dependency.

**Comment by maelle** [comment]
We could also bump the version right away if that helps!

But yes, I do not think there's any reason not to submit to CRAN. From the currently opened issues, are there some you'd want us to tackle before the submission?

**Comment by maelle** [comment]
Maybe #36 :thinking:

**Comment by zkamvar** [comment]
Good point! I completely forgot about the fact that the documentation is _ahem_ minimal :sweat_smile:

**Comment by maelle** [comment]
Actually, should we open an rOpenSci pre-submission inquiry first? It might fit as data munging.

**Comment by maelle** [comment]
(but it might also be seen as an R Markdown extension, in which case it wouldn't fit)

**Comment by zkamvar** [comment]
> Actually, should we open an rOpenSci pre-submission inquiry first? It might fit as data munging.

I think that's a good idea! I think this certainly fits within the realm of data munging since that's one of the very first things I did with it! https://carpentries.github.io/pegboard/articles/swc-survey

**Comment by maelle** [comment]
Noting that one thing I'll need to to before an actual submission is re-using (Rmd fragments) the README content for a vignette.

**Comment by etiennebacher** [comment]
Hello, I use `tinkr` as dependency in a package (thanks for this package, it's been super helpful!) which means that I can't submit to CRAN because `tinkr` is not on CRAN. Do you have some plans to submit it in the coming weeks?

**Comment by zkamvar** [comment]
Hi @etiennebacher, I think I can get something out by early-mid April. I'm finishing up some things before my vacation next week and then I can send out the package as-is to CRAN. 

My only hesitation is that #61 (which is minor, but still frustrating) and #48 are still pending changes. #48 is of particular concern because will be a major change and will force all packages using {tinkr} with {xml2} (e.g https://carpentries.github.io/pegboard/) to change the way it uses XPATH for queries.

**Comment by etiennebacher** [comment]
Hello, I was wondering if there are any news about this. I don't want to look like too much insistent on this, just want to know if we can expect {tinkr} to be on cran in the next weeks/months. I quickly took a look at #48 but I don't think I can help on this.

**Comment by zkamvar** [comment]
Hi @etiennebacher, thank you for the reminder! 

I'm sorry for the delay. I'll do my best to send it out in the next two weeks. I will reference this issue when I submit.

**Comment by etiennebacher** [comment]
Hi, just a small *bump* to know if this package will be submitted to CRAN soon

**Comment by zkamvar** [comment]
Thank you for the bump and sorry again for not getting to this. We've had a confluence of things come up that have put non-essential tasks on hold (see: https://carpentries.org/blog/2022/07/dovetail-005/), but I'll do a quiet submission and work on new features later.

**Comment by etiennebacher** [comment]
Thank you, actually I temporarily removed my tinkr dependency (by stealing some of your code) so there's no rush for me anymore. I understand this is not a priority.

**Comment by zkamvar** [comment]
I've submitted it with #73. Let's hope it passes the scrutiny of the cran team
