### ISSUE TITLE
Protect text inside curly braces?

### ISSUE THREAD

**Issue by maelle** [ropensci/tinkr#75]
In text such as

```
# Preface {.unnumbered}
```

it might be nice if the curly braces ended up in a special tag.

But we'd be limited by commonmark @zkamvar? :thinking:

**Comment by zkamvar** [comment]
AFAIK, the curlies are not special in commonmark, so the text comes out the other side unaffected:

``` r
tmp <- tempfile()
writeLines("# preface {#pre-face .unnumbered}\n\nhello", tmp)
tinkr::yarn$new(tmp)$show()
#> # preface {#pre-face .unnumbered}
#> 
#> hello
```

<sup>Created on 2022-09-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

But yeah, I think it would be good to parse these for ids, classes, and attributes if we want to also support quarto.

**Comment by zkamvar** [comment]
This would also be good to apply to links, images, and spans.

**Comment by zkamvar** [comment]
FWIW, I do process alt tags in pegboard: https://github.com/carpentries/pegboard/blob/0edf664b6a5a9f0277ffe0b712b53a0ca46f652b/R/get_images.R#L66-L97

Though I do need to refactor this to make it more general and cohesive.

**Comment by maelle** [comment]
Thank you! My issue was not clear: I would like the curly braces to become a tag for instance `{bla}` would be `<curly>{bla}</curly>` and then back to `{bla}` in Markdown. My use case is telling DeepL API to leave some tags alone so that package names don't get translated.

**Comment by maelle** [comment]
(and same for `{.unnumbered}` that does not work once translated :sweat_smile: )

**Comment by maelle** [comment]
Another element that needs curly braces: https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html

**Comment by zkamvar** [comment]
OHHHHHHH that is a good point.

At the moment, we have the `asis` attribute to help mask inline math and math blocks, and I believe we could use the same machinery to achieve this.

So a heading with curlies would be something like:

```xml
  <heading level="1">
    <text xml:space="preserve">heading </text><text asis="true">{.unnumbered}</text>
  </heading>
```

**Comment by maelle** [comment]
Oh, that's a nice structure!

I can only tell DeepL API to ignore some tags but I could transform the tags before and after sending them to the API, based on `asis`. :thinking:
