### ISSUE TITLE
filter out / replace special control characters

### ISSUE THREAD

**Issue by zkamvar** [ropensci/tinkr#96]
I'm running into a fun situation where someone added a `\v` control character to the end of a list and I'm getting a `PCDATA invalid Char value 11` error.

There is an answer in SO that [describes how to detect and replace the bad character with a blank](https://stackoverflow.com/questions/26408727/pcdata-invalid-char-in-r), so we can take that and add it to the pre-processing step.

NOTE: Since I can hear Nero fiddling on the outskirts of SO, here's the solution:

```r
    illegal <- "[^\u0009\u000a\u000d\u0020-\uD7FF\uE000-\uFFFD]" 
    
    utf8_for_xml <- function(x) {
        
        return(gsub(illegal, "", x))
        
        }

    string_formatted <- utf8_for_xml(string)
```

I believe this is the correct way to do it since these characters shouldn't exist in the document in the first place. That being said, it's a bit frustrating to find out what these characters actually do, but I've found these resource:

- https://en.wikipedia.org/wiki/Control_character
- https://en.wikipedia.org/wiki/Valid_characters_in_XML#XML_1.1

**Comment by maelle** [comment]
:open_mouth: and :clap:
